In [30]:
import tensorflow as tf


In [3]:
#Intro to tensorflow
a=tf.constant("Hii Bhanu")
sess=tf.Session()
print(sess.run(a))

b'Hii Bhanu'


In [4]:
sess.close()

In [11]:
#Session formats
a1=tf.constant([[2,3]])
a2=tf.constant([[4],[5]])
dot=tf.matmul(a1,a2)
#method 1
sess=tf.Session()
res=sess.run(dot)
print(res)
sess.close()

[[23]]


In [13]:
#method 2
with tf.Session() as sess:
    res=sess.run(dot)
    print(res)

[[23]]


In [16]:
#Tensors
#Variable
t1=tf.Variable('Bhanu',tf.string)
print(t1)

<tf.Variable 'Variable_2:0' shape=() dtype=string_ref>


In [20]:
#Constant
t2=tf.constant(1,tf.int16)
t3=tf.constant(1.14141,tf.float32)
print(t2,t3)

Tensor("Const_21:0", shape=(), dtype=int16) Tensor("Const_22:0", shape=(), dtype=float32)


In [22]:
#1 dimensional tensor
t1=tf.constant([1,3,5],tf.int16)
t2=tf.constant([True,False,True],tf.bool)
print(t1,t2)

Tensor("Const_24:0", shape=(3,), dtype=int16) Tensor("Const_25:0", shape=(3,), dtype=bool)


In [23]:
#2 dimensions
t1=tf.constant([[1,2],[4,5]],tf.int16)
print(t1)

Tensor("Const_26:0", shape=(2, 2), dtype=int16)


In [25]:
#3 dimensions
t1=tf.constant([[[1,2],[4,5],[7,8]]],tf.int16)
print(t1)

Tensor("Const_28:0", shape=(1, 3, 2), dtype=int16)


In [26]:
t1.shape

TensorShape([Dimension(1), Dimension(3), Dimension(2)])

In [35]:
#Reshape
sess=tf.Session()
t1=tf.constant([1,2,3,4,5,6,7,8,9],tf.int32)
t1=tf.reshape(t1,[3,3])
print(sess.run(t1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
from tensorflow.python.framework import ops

#Defining variables
weights=tf.Variable(tf.random_normal([2,3],stddev=0.1),name='weights')
biases_K=tf.Variable(tf.zeros([3]),name="biases")
cust_var=tf.Variable(tf.ones([3]),name="cust")

#------------------------------------------------------------------
#Storing the variables in a list
all_list=ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES)

#Customized Initialization
cust_list=[weights,biases]
init_cust=tf.variables_initializer(var_list=cust_list)
#---------------------------------------------------------------------
#All Variable initialization
all_init=tf.initialize_all_variables()
#Running Session
with tf.Session() as sess:
    sess.run(init_cust)
    sess.run(all_init)
    print(cust_var)




<tf.Variable 'cust_14:0' shape=(3,) dtype=float32_ref>


In [67]:
#Defining variable 
weights=tf.Variable(tf.random_normal([2,3],stddev=0.1),name='weights')
biases_K=tf.Variable(tf.zeros([3]),name="biases")
#Variables Initialization
init_wt=tf.initialize_all_variables()
#Running session 
sess=tf.Session()
sess.run(init_wt)
print("Weights are",sess.run(weights),"and biases are",sess.run(biases))
sess.close()

Weights are [[ 0.17729948  0.150569   -0.09898481]
 [ 0.00245347  0.14578752 -0.05407009]] and biases are [0. 0. 0.]


In [87]:
#Operations
a=tf.constant([2,3],tf.float32)
b=tf.constant([4,5],tf.float32)
with tf.Session() as sess:
    print(sess.run(tf.add(a,b)))
    print(sess.run(tf.subtract(a,b)))
    print(sess.run(tf.div(a,b)))
    print(sess.run(tf.multiply(a,b)))
    print(sess.run(tf.pow(a,b)))
    print(sess.run(tf.sqrt(a)))
    print(sess.run(tf.exp(b)))


[6. 8.]
[0.5 0.6]
[ 8. 15.]
[ 16. 243.]
[-2. -2.]
[1.4142135 1.7320508]
[ 54.59815 148.41316]
